# application-local.yaml takes over from application.properties for the port, but not for the rest
server:
  port: 8088
spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: MySqlR00t
  thymeleaf:
    prefix: classpath:/templates/
    suffix: ""
  jpa:
    show-sql: true
management:
  tracing:
    sampling:
      probability: 1
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 5000
  supported-currencies: USD,EUR,GBP
