server:
  port: 8089
spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: MySqlR00t
  thymeleaf:
    prefix: classpath:/templates/
    suffix: ""
  jpa:
    show-sql: true
management:
  tracing:
    sampling:
      probability: 1
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 5000
  supported-currencies: USD,EUR,GBP,JPY
# application.yaml takes over from application.properties or in this case application-local.yaml
# if there is an error (formatting or otherwise) in any configfile, the application will not start
